# Autogenerated by devscripts/update-version.py

__version__ = '2024.06.27.020218'

RELEASE_GIT_HEAD = '9436822127e5f09d50aea844e352359b30c4aefa'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'master'

ORIGIN = 'Razinal/yt-dlp'

_pkg_version = '2024.06.27.020218'
