# Autogenerated by devscripts/update-version.py

__version__ = '2024.06.27.064310'

RELEASE_GIT_HEAD = '7631b61a74f611fa34b62d309d733ce5e1ceae84'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'master'

ORIGIN = 'Razinal/yt-dlp'

_pkg_version = '2024.06.27.064310'
