# Autogenerated by devscripts/update-version.py

__version__ = '2024.06.27.031251'

RELEASE_GIT_HEAD = 'd94776f369ab56c26395b44f67bf923448434109'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'master'

ORIGIN = 'Razinal/yt-dlp'

_pkg_version = '2024.06.27.031251'
